### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by gromgit** [MiJyn/openlux#6]
Since you've just incremented the version number, can I suggest at least tagging each new version release going forward? This way, anyone who needs to use an older release for whatever reason can do so without having to go through the entire commit log manually to find each "bump" reference.

Thanks!

**Comment by AnonymousMeerkat** [comment]
Thank you for the idea!! I will do it once I wake up tomorrow :)

**Comment by AnonymousMeerkat** [comment]
Done!
