### ISSUE TITLE
is this project a fork?

### ISSUE THREAD

**Issue by rhetr** [MiJyn/openlux#8]
Is this project a fork of [this one](https://gitlab.com/AnonymousMeerkat/openlux)? my git remote from september suggests that it is-- I think it should be stated in the readme

**Comment by rhetr** [comment]
did some more searching and uhh, i guess you just renamed your account or something? I am confused but whatever, closed

**Comment by AnonymousMeerkat** [comment]
Yes, same project, that one is just a mirror :)
